# Simple workflow for deploying static content to GitHub Pages
name: Update hackspace data

on:
  # Runs on pushes targeting the default branch
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  # Single deploy job since we're just deploying
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Fetch data
        run: |
          deno run -A leaderboard.ts fetch
      - uses: EndBug/add-and-commit@v9
        name: Commit data
        with:
          add: "scores.json index.html"
          commit: --signoff
          default_author: github_actions
          message: "Update data"
          push: true
